import re
from pathlib import Path

SUMMARIES_DIR = Path('data/summaries')

def generate_bibtex(title, authors_str, year, journal, doi, link):
    # Parsing Authors
    authors = [a.strip() for a in authors_str.split(',')]
    
    first_author_surname = 'Unknown'
    if authors:
        first = authors[0]
        # Heuristic: Last word
        first_author_surname = first.split(' ')[-1]
    
    first_author_surname = ''.join(c for c in first_author_surname if c.isalnum())
    
    # Title word
    title_word = 'Article'
    words = [w for w in title.split() if w.lower() not in {'a', 'an', 'the', 'on', 'in', 'of'}]
    if words:
        title_word = ''.join(c for c in words[0] if c.isalnum())
        
    citation_key = f'{first_author_surname}{year}{title_word}'
    
    # Format authors for BibTeX (Last, First)
    formatted_authors = []
    for author in authors:
        parts = author.split(' ')
        if len(parts) > 1:
            last = parts[-1]
            first = ' '.join(parts[:-1])
            formatted_authors.append(f'{last}, {first}')
        else:
            formatted_authors.append(author)
            
    bib_authors = ' and '.join(formatted_authors)
    
    bibtex = f'@article{{{citation_key},\n'
    bibtex += f'  author = {{{bib_authors}}},\n'
    bibtex += f'  title = {{{title}}},\n'
    bibtex += f'  journal = {{{journal}}},\n'
    bibtex += f'  year = {{{year}}}'
    
    if doi:
        # Extract clean DOI from [doi](url) or just doi
        clean_doi = doi
        if '[' in doi and ']' in doi:
            clean_doi = doi.split('[')[1].split(']')[0]
        bibtex += f',\n  doi = {{{clean_doi}}}'
        bibtex += f',\n  url = {{https://doi.org/{clean_doi}}}'
    elif link:
         bibtex += f',\n  url = {{{link}}}'
         
    bibtex += '\n}'
    return bibtex

count = 0
for md_file in SUMMARIES_DIR.glob('**/*.md'):
    content = md_file.read_text()
    
    # Check if empty citation block exists (from previous failed run)
    # The previous run likely added "## Citation\n\n\n\n---" or something similar due to missing interpolation
    if "## Citation" in content:
        # Check if it looks empty (no @article)
        if "@article" not in content:
            # We need to remove the bad block and re-add
            # Remove from ## Citation down to --- or end
            content = re.sub(r'\n\n## Citation.*?(?=\n\n---|\Z)', '', content, flags=re.DOTALL)
        else:
            # Already has valid bibtex
            continue
        
    # Extract metadata
    try:
        lines = content.splitlines()
        
        # Title (First line # ...)
        title = 'Unknown Title'
        for line in lines:
            if line.startswith('# '):
                # Remove # Author (Year)
                # Matches: # Surname (YYYY) Title
                parts = line.split(') ', 1)
                if len(parts) > 1:
                    title = parts[1].strip()
                else:
                    title = line[2:].strip()
                break
                
        # Metadata section
        journal = 'Unknown Journal'
        year = '2026'
        authors_str = 'Unknown'
        doi = ''
        
        in_id_section = False
        for line in lines:
            if line.startswith('## Identification'):
                in_id_section = True
                continue
            if in_id_section and line.startswith('## '):
                in_id_section = False
                break
                
            if in_id_section:
                if '- **Journal:**' in line:
                    journal = line.split('**Journal:**')[1].strip()
                elif '- **Year:**' in line:
                    year = line.split('**Year:**')[1].strip()
                elif '- **Authors:**' in line:
                    authors_str = line.split('**Authors:**')[1].strip()
                elif '- **DOI:**' in line:
                    doi = line.split('**DOI:**')[1].strip()
        
        # Link from footer
        link = ''
        if '<!-- metadata:original_link:' in content:
            link = content.split('<!-- metadata:original_link:')[1].split(' -->')[0].strip()

        bibtex = generate_bibtex(title, authors_str, year, journal, doi, link)
        
        # Insert before footer (---)
        if '\n---\n*Generated by' in content:
            parts = content.split('\n---\n*Generated by')
            new_content = parts[0] + f'\n\n## Citation\n```bibtex\n{bibtex}\n```' + '\n\n---\n*Generated by' + parts[1]
            md_file.write_text(new_content)
            count += 1
        else:
            # Append if footer not found (fallback)
            md_file.write_text(content + f'\n\n## Citation\n```bibtex\n{bibtex}\n```')
            count += 1
            
    except Exception as e:
        print(f'Error processing {md_file}: {e}')

print(f'Fixed {count} files.')
